blank_issues_enabled: false
contact_links:
  - name: ğŸ Bug
    url: https://github.com/Likelion-at-SMWU-13th/Spotal-BE/issues/new?template=bug.yml
    about: ë²„ê·¸ ì œë³´
  - name: ğŸš€ Deploy
    url: https://github.com/Likelion-at-SMWU-13th/Spotal-BE/issues/new?template=deploy.yml
    about: ë°°í¬ ê´€ë ¨ ì‘ì—…
  - name: âœ¨ Feature
    url: https://github.com/Likelion-at-SMWU-13th/Spotal-BE/issues/new?template=feature.yml
    about: ìƒˆë¡œìš´ ê¸°ëŠ¥ ì¶”ê°€
  - name: ğŸ›  Refactor
    url: https://github.com/Likelion-at-SMWU-13th/Spotal-BE/issues/new?template=refactor.yml
    about: ë¦¬íŒ©í† ë§
